### ISSUE TITLE
Spinner doesn't work after updating react to 16.2.0

### ISSUE THREAD

**Issue by anna-kartynnik** [tsuyoshiwada/react-md-spinner#12]
Hello, 

I've updated react to 16.2.0 and now sometimes spinner works but sometimes it doesn't. When it doesn't work I can see only 4x4 square
![screen shot 2018-03-20 at 12 34 20](https://user-images.githubusercontent.com/15210801/37646572-131b74ca-2c3b-11e8-9483-57216f1340aa.png)

So far the only difference I've noticed between components that work and don't work is that components that work have `_owner: null` and components that don't work have `_owner` property that is not empty, they have FiberNode as _owner. 

I've just found that and honestly I don't know where to look at. If you have any ideas about what causes my problems, it'll be much appreciated. Thanks!

**Comment by tsuyoshiwada** [comment]
Hi @anna-kartynnik, Thank you for report :pray:

When using `react @ 16.2.0` in my environment, I could not reproduce the error...
If possible, it would be extremely helpful to provide reproducible minimum code :raised_hands:

**Comment by anna-kartynnik** [comment]
Hm, it's interesting, I can't reproduce the issue in another environment (at work). I'll try to create reproducible code once I get home.

**Comment by anna-kartynnik** [comment]
I'm closing it because I can't reproduce it anymore.

**Comment by tsuyoshiwada** [comment]
Thank you for confirming!
Also, if you can reproduce the same problem I'd be happy if you open Issue :pray:

**Comment by flcli** [comment]
@anna-kartynnik I'm actually running into this exact issue. Did you do anything at all to fix it?

**Comment by anna-kartynnik** [comment]
No, no changes from my side. As far as I remember, when I updated browser or something like that it just started working again. Not clear for me anyway...

**Comment by flcli** [comment]
@tsuyoshiwada I think I have a diagnosis...

This seems to be happening when there are 2 spinners. I'm also using react-transition-group, but I'm not sure if it matters. 

My use case and flow looks like this on a single page:
1. Spinner 1 renders and spins correctly
2. Spinner 1 unmounts
3. Spinner 2 renders, but does not spin
