### ISSUE TITLE
Server-Side  Rendering

### ISSUE THREAD

**Issue by cescoferraro** [tsuyoshiwada/react-md-spinner#3]
I noticed that the spinner only start once the whole bundle is loaded on the page. 
I am missing the whole point of showing the spinner at the first place.
Using the spinner to load asynchronous routes, so I want to show the spinner before things get loaded on the client side. 
I wonder if there is something inside the the spin movement that requires javascript actions? Cant it work 100% off css stuff?

**Comment by tsuyoshiwada** [comment]
hi @cescoferraro , thanks for issues.

react-md-spinner uses the module [css-keyframer.js](https://github.com/tsuyoshiwada/css-keyframer) for embedding `@keyframe`.
Since `@keyframe` is embedded in `<head>` through `css-keyframer.js`, animation starts for the first time after building the DOM.

---

This is one idea.
When doing server-side rendering, problems may be solved by injecting `@keyframe` into `<head>` as follows.

```javascript
import React from "react";
import { renderToString } from "react-dom/server";
import { SSRBehaviour } from "react-md-spinner";
import App from "./App";

const html = content => (`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    ${SSRBehaviour.createKeyframes()}
  </head>
  <body>
    <div id="app">${content}</div>
    <script src="./bundle.js"></script>
  </body>
</html>
`);

const render() => {
  res.status(200).send(html(renderToString(<App />)));
};

export default render;
```


What do you think of this idea?

**Comment by cescoferraro** [comment]
@tsuyoshiwada I wish it works but I could not `import { SSRBehaviour } from "react-md-spinner";` because it return undefined. Could not also find a single reference to SSRBehaviour on the repo's source code.

**Comment by tsuyoshiwada** [comment]
@cescoferraro 

> because it return undefined.

Sorry 🙇 ! This is unimplemented API yet.

> Are you thinking of implementing this? Sounds nice!

Thanks! I'd like to release a new version that implemented the API next week.

**Comment by cescoferraro** [comment]
@tsuyoshiwada let me know as soon as you release. The spinner looks awesome for this project I am working on

**Comment by cescoferraro** [comment]
@tsuyoshiwada
We want to be able to use the spinner [here](https://github.com/ctrlplusb/react-async-component#api) 
It seems like the best aproach for code splitting I have found so far.

> Loading (Component, Optional, default: null) : A Component to be displayed whilst your async Component is being resolved. It will be provided the same props that will be provided to your resolved async Component.

**Comment by tsuyoshiwada** [comment]
@cescoferraro 

I've never used react-async-component. :cry:

---

The correspondence of SSR is scheduled to be completed tomorrow or the day after tomorrow.

I would be grateful if you try out combination of `react-async-component` and `react-md-spinner`. after released the new version.

**Comment by tsuyoshiwada** [comment]
@cescoferraro 
Just it has been updated to v0.2.0 :tada:

Please check when you have time.
Thanks!

**Comment by cescoferraro** [comment]
it works! its awesome! thanks @tsuyoshiwada

**Comment by tsuyoshiwada** [comment]
@cescoferraro You are welcome. Thanks :smiley:
