### ISSUE TITLE
React 15.5.0 warning

### ISSUE THREAD

**Issue by anna-kartynnik** [tsuyoshiwada/react-md-spinner#5]
Hello, after updating to react 15.5.0 I can see the following warning in the browser console

    Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
        printWarning @ warning.js:36
        warning @ warning.js:60
        get @ React.js:95
        (anonymous) @ index.js:112 (react-md-spinner/lib/index.js:112)

More about [changes in 15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

**Comment by tsuyoshiwada** [comment]
Hi @anna-kartynnik. Thanks for Issues.

I'm going to remove `prop-types` and switch to Flowtype.
planning to respond to the weekend :+1:

**Comment by tsuyoshiwada** [comment]
Hi @anna-kartynnik.
The correspondence to the `prop-types` package has been completed. ([#6](https://github.com/tsuyoshiwada/react-md-spinner/pull/6))

**Comment by anna-kartynnik** [comment]
hi @tsuyoshiwada thanks! 👍
